name: build and deploy annealing

on:
  # run manually
  workflow_dispatch:
  # run on dev branches
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - '.github/workflows/annealing-build.yaml'
#    branches:
#      - "release/annealing/v**"
#      - '**'
#      - "main"
env:
  SERVICE_NAME: 'annealing-service'
  SERVICE_PATH: 'services/annealing-service'
jobs:
  build:

    name: Build the thing
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set variables
      run: |
        if [[ $"${{github.event_name}}" == "push" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=dev" >> $GITHUB_ENV
        fi
    - name: echo
      run: |
        echo '...building'
        echo $ENV
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: deploy
      run: |
        python .github/workflows/deploy.py --env $ENV
    - name: publish release
      run: |
        echo "endpoint=$(cat somefile) >> $GITHUB_ENV
        echo "version=$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV
        echo "tag=${{ env.SERVICE_NAME}}/$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.SERVICE_NAME }}
        tag: ${{ env.tag}}

