name: build and deploy annealing

on:
  # run manually
  workflow_dispatch:
  # run on dev branches
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - '.github/workflows/annealing-build.yaml'
#    branches:
#      - "release/annealing/v**"
#      - '**'
#      - "main"
jobs:
  build:

    name: Build the thing
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set variables
      run: |
        if [[ $"${{github.event_name}}" == "push" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=dev" >> $GITHUB_ENV
        fi
    - name: echo
      run: |
        echo '...building'
        echo $ENV
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: deploy
      run: |
        python .github/workflows/deploy.py --env $ENV
    - name: publish release
      run: |
        cat somefile
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false


