name: deploy parser

on:
  # run manually
  workflow_dispatch:
  # run on dev branches
#  push:
#    branches:
#      - "main"
  push:
    branches:
      - 'parser/**'
    paths:
      - '.github/workflows/parser-build.yaml'
      - 'services/parser-service/**'
#    branches:
#      - '**'
#      - "main"
env:
  SERVICE_NAME: 'parser-service'
  SERVICE_PATH: 'services/parser-service'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: description
      id: get_service_description
      uses: mikefarah/yq@master
      with:
        cmd: yq '.description' 'services/parser-service/version.yaml'

    - name: version
      id: get_version
      uses: mikefarah/yq@master
      with:
        cmd: yq '.version' 'services/parser-service/version.yaml'

    - name: version notes
      id: get_version_notes
      uses: mikefarah/yq@master
      with:
        cmd: yq '.version_notes' 'services/parser-service/version.yaml'

    - name: set variables
      run: |
        if ${{ github.ref == 'refs/heads/main' }}; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=dev" >> $GITHUB_ENV
        fi

    - name: echo
      run: |
        echo '...building'
        echo $ENV

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: deploy
      run: |
        python .github/workflows/deploy.py --env $ENV
    outputs:
      version: ${{ steps.get_version.outputs.result }}
      version_notes: ${{ steps.get_version_notes.outputs.result }}
      service_description: ${{ steps.get_service_description.outputs.result }}

  deploy:
    permissions:
      deployments: write
      contents: write

#    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: release vars
        run: |
          echo "version=${{ steps.get_service_version.outputs.result }}" >> $GITHUB_ENV
          echo "tag=${{ env.SERVICE_NAME}}/$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV
          echo "endpoint=$(cat somefile)" >> $GITHUB_ENV
          if ${{ github.ref == 'refs/heads/main' }}; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: deploy
        run: |
          python .github/workflows/deploy.py --env $ENV

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: ${{ env.ENV }}
          payload: '{"endpoint": "${{ env.endpoint }}", "service": "${{ env.SERVICE_NAME }}", "version":"${{ needs.build.outputs.version }}", "version_notes": "${{ needs.build.outputs.version_notes}}" }'
          production-environment: github.ref == 'refs/heads/main'
          description: ${{ needs.build.outputs.service_description }}
          auto-inactive: github.ref == 'refs/heads/main'
          initial-status: success

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SERVICE_NAME}}/${{ needs.build.outputs.version }}"
          title: "${{ env.SERVICE_NAME }}/${{ needs.build.outputs.version }}"

      - name: deploy ${{ needs.build.outputs.version }}
        run: |
          echo "======================== Your application is available at: ========================"
          echo 'done'
          echo "${{ needs.build.outputs.version }}"
          echo "==================================================================================="
