name: deploy parser

on:
  # run manually
  workflow_dispatch:
  # run on dev branches
#  push:
#    branches:
#      - "main"
  pull_request:
    paths:
      - '.github/workflows/parser-build.yaml'
      - 'services/parser-service/**'
#    branches:
#      - '**'
#      - "main"
env:
  SERVICE_NAME: 'parser-service'
  SERVICE_PATH: 'services/parser-service'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: description
      id: get_service_description
      uses: mikefarah/yq@master
      with:
        cmd: yq '.description' 'services/parser-service/version.yaml'

    - name: version
      id: get_version
      uses: mikefarah/yq@master
      with:
        cmd: yq '.version' 'services/parser-service/version.yaml'

    - name: version notes
      id: get_version_notes
      uses: mikefarah/yq@master
      with:
        cmd: yq '.version_notes' 'services/parser-service/version.yaml'

    - name: set variables
      run: |
        if ${{ github.ref == 'refs/heads/main' }}; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=dev" >> $GITHUB_ENV
        fi
    - name: echo
      run: |
        echo '...building'
        echo $ENV
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: deploy
      run: |
        python .github/workflows/deploy.py --env $ENV

  dev-deploy:
    permissions:
      deployments: write

    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: release vars
        run: |
          echo "version=${{ steps.get_service_version.outputs.result }}" >> $GITHUB_ENV
          echo "tag=${{ env.SERVICE_NAME}}/$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: dev
          payload: '{"endpoint": 89483999222, "service": "${{ env.SERVICE_NAME }}", "version":"${{ steps.get_version.outputs.result }}", "version_notes": "${{ steps.get_version_notes.outputs.result }}" }'
          description: ${{ steps.get_service_description.outputs.result }}
          auto-inactive: true
          initial-status: success

      - name: deploy ${{ env.version }}
        run: |
          echo "======================== Your application is available at: ========================"
          echo 'done'
          echo "${{ env.version }}"
          echo "==================================================================================="
  production-deploy:
    permissions:
      deployments: write
      contents: write

    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: eploy
        run: |
          echo 'done'

      - name: release vars
        run: |
          echo "version=$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV
          echo "tag=${{ env.SERVICE_NAME}}/$(cat $SERVICE_PATH/version)" >> $GITHUB_ENV

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SERVICE_NAME}}/${{ env.version }}"
          title: "${{ env.SERVICE_NAME }}/${{ env.version }}"

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: prod
          payload: '{"endpoint": 89483999222, "service": "${{ env.SERVICE_NAME }}", "version":"${{ env.version }}" }'
          production-environment: true
          description: foobar
          auto-inactive: false
          initial-status: success
